# Generated by Django 4.2 on 2023-04-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0002_remove_content_content_content_caption_content_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["-schadule"]},
        ),
    ]
