# Generated by Django 4.2 on 2023-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_content_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="is_reel",
        ),
    ]
